all:demo07 demo08 demo10 demo11 demo12 demo13 demo14 demo20 demo31 demo32 demo33

demo07:demo07.cpp
	g++ -g -o demo07 demo07.cpp ../_public.cpp -lm -lc

demo08:demo08.cpp
	g++ -g -o demo08 demo08.cpp ../_public.cpp -lm -lc

demo10:demo10.cpp
	g++ -g -o demo10 demo10.cpp ../_public.cpp -lm -lc

demo11:demo11.cpp
	g++ -g -o demo11 demo11.cpp ../_public.cpp -lm -lc

demo12:demo12.cpp
	g++ -g -o demo12 demo12.cpp ../_public.cpp -lm -lc

demo13:demo13.cpp
	g++ -g -o demo13 demo13.cpp ../_public.cpp -lm -lc

demo14:demo14.cpp
	g++ -g -o demo14 demo14.cpp ../_public.cpp -lm -lc

demo20:demo20.cpp
	g++ -g -o demo20 demo20.cpp ../_public.cpp -lpthread -lm -lc

demo31:demo31.cpp
	g++ -g -o demo31 demo31.cpp ../_public.cpp -lm -lc

demo32:demo32.cpp
	g++ -g -o demo32 demo32.cpp ../_public.cpp -lm -lc

demo33:demo33.cpp
	g++ -g -o demo33 demo33.cpp ../_public.cpp -lm -lc

clean:
	rm demo07 demo08 demo10 demo11 demo12 demo13 demo14 demo20 demo31 demo32 demo33
