all:demo07 demo10 demo11 demo12 demo13

demo07:demo07.cpp
	g++ -g -o demo07 demo07.cpp ../_public.cpp -lm -lc

demo10:demo10.cpp
	g++ -g -o demo10 demo10.cpp ../_public.cpp -lm -lc

demo11:demo11.cpp
	g++ -g -o demo11 demo11.cpp ../_public.cpp -lm -lc

demo12:demo12.cpp
	g++ -g -o demo12 demo12.cpp ../_public.cpp -lm -lc

demo13:demo13.cpp
	g++ -g -o demo13 demo13.cpp ../_public.cpp -lm -lc

clean:
	rm demo07 demo10 demo11 demo12
